### PR TITLE
feat: convert navbar and footer to follow new designs

### PR DESCRIPTION
**Pull request by BryanPan342**
* edited navbar to reflect redesign
* edited footer to follow redesign

**considering to make the navbar scrollTop interaction either a custom hook and/or a callback**

Fixes: #80
Fixes: #81

### CODE REVIEW

**Review by arjunr00 — COMMENTED** [review]
This is a small design thing but do you think we should have some visual feedback when mousing over links in the navbar and footer? LGTM other than that

**Comment by BryanPan342** [comment]
@arjunr00 i was thinking about adding microinteractions later..

But if u want we can do an underline or smth?

See #85

**Comment by arjunr00** [comment]
ye fair enough

**Review by arjunr00 — APPROVED** [review]

**Review by arjunr00 — APPROVED** [review]
ligitim

**Pull request merged**
